services:
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    container_name: mongodb_repairs
    networks:
      - repairs-network

  ex1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ex1_api
    ports:
      - "16025:16025"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/autoRepair
    depends_on:
      - mongodb
    networks:
      - repairs-network

  ex2:
    build:
      context: ../ex2
      dockerfile: Dockerfile.interface
    container_name: ex2_interface
    ports:
      - "16026:16026"
    environment:
      - API_URL=http://ex1:16025/repairs
    depends_on:
      - ex1
    networks:
      - repairs-network

networks:
  repairs-network:
    driver: bridge
